spring
  application
    name: Config-dev
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true   #default true
    service-url:
      defaultZone: http://localhost:8761/eureka   #basically it says will register with this url on the server
